# Generated by Django 5.2 on 2025-05-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
