# Generated by Django 5.2 on 2025-05-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_postworkflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptions',
            new_name='description',
        ),
    ]
