# Generated by Django 4.2.20 on 2025-05-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
