# Generated by Django 4.2.20 on 2025-05-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0011_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
